# Generated by Django 5.0.4 on 2024-04-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('change_1h', models.FloatField()),
                ('change_24h', models.FloatField()),
                ('change_7d', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('volume_24h', models.FloatField()),
                ('circulating_supply', models.FloatField()),
            ],
        ),
    ]
